package miniJava.SyntacticAnalyzer;

public enum TokenKind {EOT, CLASS, ID, SEMIC, COMMA, PERIOD, LPAREN, RPAREN, LSQUARE, RSQUARE, 
	LCURLY, RCURLY, NEW, VOID, PUBLIC, PRIVATE, STATIC, INT, BOOL, THIS, RETURN, IF, ELSE, WHILE,
	EQUALS, UNOP, BINOP, NUM, TRUE, FALSE, ERROR, MINUS}
